include:
  - project: 'experiments/ci-templates'
    ref: 'development'
    file: 'templates/cd-templates.yml'

variables:
  DEPLOY_SERVER: "mars.butterflycluster.com"
  DEPLOY_USER: "deploy_sa"
  DEPLOY_PATH: "/apps/myapp"
  ENV_NAME: "production"

  PRE_DEPLOY_CMD: "df -h; free -m"
  BACKUP_CMD: "tar czf ${DEPLOY_PATH}/backup-$(date +%s).tgz ${DEPLOY_PATH}"
  STOP_CMD: "bash ${DEPLOY_PATH}/scripts/stop.sh"
  START_CMD: "bash ${DEPLOY_PATH}/scripts/start.sh"
  VERIFY_CMD: "curl -sSf http://localhost:8080/health"
  SMOKE_CMD: "bash ${DEPLOY_PATH}/scripts/smoke_test.sh"
  CLEANUP_CMD: "rm -f ${DEPLOY_PATH}/*.log; find ${DEPLOY_PATH}/tmp -mtime +7 -delete"

stages:
  - pre_deploy
  - deploy
  - post_deploy

# Anchored reusable SSH script template
.ssh_script_template: &ssh_script
  extends: .base_deploy
  script:
    - 'echo "Running command: $COMMAND"'
    - 'sshpass -e ssh ${SSH_OPTS} ${DEPLOY_USER}@${DEPLOY_SERVER} "$COMMAND"'

# Command execution jobs using overridden COMMAND per job

pre_deploy:
  <<: *ssh_script
  stage: pre_deploy
  variables:
    COMMAND: "${PRE_DEPLOY_CMD}"

transfer_code:
  extends: .base_deploy
  stage: deploy
  script:
    - 'echo "Transferring code to ${DEPLOY_SERVER}"'
    - 'git archive --format=tar.gz ${CI_COMMIT_SHA} -o code.tar.gz'
    - 'sshpass -e scp ${SSH_OPTS} code.tar.gz ${DEPLOY_USER}@${DEPLOY_SERVER}:${DEPLOY_PATH}/'
    - 'sshpass -e ssh ${SSH_OPTS} ${DEPLOY_USER}@${DEPLOY_SERVER} "cd ${DEPLOY_PATH} && tar xzf code.tar.gz && rm code.tar.gz"'

backup_current:
  <<: *ssh_script
  stage: deploy
  variables:
    COMMAND: "${BACKUP_CMD}"
  needs: [transfer_code]

stop_app:
  <<: *ssh_script
  stage: deploy
  variables:
    COMMAND: "${STOP_CMD}"
  needs: [backup_current]

start_app:
  <<: *ssh_script
  stage: deploy
  variables:
    COMMAND: "${START_CMD}"
  needs: [stop_app]

verify_health:
  <<: *ssh_script
  stage: post_deploy
  variables:
    COMMAND: "${VERIFY_CMD}"
  needs: [start_app]

smoke_tests:
  <<: *ssh_script
  stage: post_deploy
  variables:
    COMMAND: "${SMOKE_CMD}"
  needs: [verify_health]

cleanup:
  <<: *ssh_script
  stage: post_deploy
  variables:
    COMMAND: "${CLEANUP_CMD}"
  needs: [smoke_tests]
  
  
  