include:
  - project: 'experiments/cd-templates'
    ref: 'development'
    file: 'templates/cd-templates.yml'

variables:
  APP_NAME: "dashboard"
  DEPLOY_SERVER: "mars.butterflycluster.com"
  DEPLOY_USER: "deploy_sa"
  ENV_NAME: "mars"

  PRE_DEPLOY_CMD: "df -h; free -m"
  STOP_CMD: "cd ${CURRENT_LINK} && bash bin/manage.sh stop ${ENV_NAME}"
  START_CMD: "cd ${CURRENT_LINK} && bash bin/manage.sh start ${ENV_NAME}"
  VERIFY_CMD: "curl -sSf http://localhost:8050/overview"
  SMOKE_CMD: "cd ${CURRENT_LINK} && bash bin/manage.sh smoke ${ENV_NAME}"
  CLEANUP_CMD: "true"
  NOTIFY_CMD: "echo 'Notify: ${APP_NAME} deployed @ ${DEPLOY_TIMESTAMP}'"

stages:
  - pre_deploy
  - deploy
  - post_deploy

pre_deploy:
  extends: .ssh_script_template
  stage: pre_deploy
  variables:
    COMMAND: "${PRE_DEPLOY_CMD}"

prepare_release_dir:
  extends: .prepare_release_dir_template

upload_code:
  extends: .upload_code_template

extract_and_link:
  extends: .extract_and_link_template

backup_current:
  extends: .ssh_script_template
  stage: deploy
  variables:
    COMMAND: "${BACKUP_CMD}"
  needs:
    - extract_and_link

stop_app:
  extends: .ssh_script_template
  stage: deploy
  variables:
    COMMAND: "${STOP_CMD}"
  needs:
    - backup_current

start_app:
  extends: .ssh_script_template
  stage: deploy
  variables:
    COMMAND: "${START_CMD}"
  needs:
    - stop_app

verify_health:
  extends: .ssh_script_template
  stage: post_deploy
  variables:
    COMMAND: "${VERIFY_CMD}"
  needs:
    - start_app

smoke_tests:
  extends: .ssh_script_template
  stage: post_deploy
  variables:
    COMMAND: "${SMOKE_CMD}"
  needs:
    - verify_health

cleanup:
  extends: .ssh_script_template
  stage: post_deploy
  variables:
    COMMAND: "${CLEANUP_CMD}"
  needs:
    - smoke_tests

notify:
  extends: .ssh_script_template
  stage: post_deploy
  variables:
    COMMAND: "${NOTIFY_CMD}"
  needs:
    - cleanup


