include:
  - project: 'experiments/ci-templates'
    ref: 'development'
    file: 'templates/cd-templates.yml'

variables:
  APP_NAME: "dashboard"
  DEPLOY_SERVER: "mars.butterflycluster.com"
  DEPLOY_USER: "deploy_sa"
  ENV_NAME: "mars"
  DEPLOY_BASE_PATH: "/apps/data/${APP_NAME}"
  RELEASES_DIR: "${DEPLOY_BASE_PATH}/releases"
  CURRENT_LINK: "${DEPLOY_BASE_PATH}/current"
  DEPLOY_TIMESTAMP: "$(date +%Y%m%d_%H%M%S)"

  PRE_DEPLOY_CMD: "df -h; free -m"
  BACKUP_CMD: "mkdir -p ${DEPLOY_BASE_PATH}/backups && tar --ignore-failed-read -czf ${DEPLOY_BASE_PATH}/backups/backup-$(date +%s).tgz -C ${CURRENT_LINK} . || [ $? -eq 1 ]"
  STOP_CMD: "cd ${CURRENT_LINK} && bash bin/manage.sh stop ${ENV_NAME}"
  START_CMD: "cd ${CURRENT_LINK} && bash bin/manage.sh start ${ENV_NAME}"
  VERIFY_CMD: "curl -sSf http://localhost:8050/overview"
  SMOKE_CMD: "cd ${CURRENT_LINK} && bash bin/manage.sh smoke ${ENV_NAME}"
  CLEANUP_CMD: "true"
  NOTIFY_CMD: "echo 'Notify: deployment completed for ${APP_NAME} @ ${DEPLOY_TIMESTAMP}'"

stages:
  - pre_deploy
  - deploy
  - post_deploy

# SSH wrapper for simple commands
.ssh_script_template: &ssh_script
  extends: .base_deploy
  script:
    - 'echo "Running command: $COMMAND"'
    - 'sshpass -e ssh ${SSH_OPTS} ${DEPLOY_USER}@${DEPLOY_SERVER} "$COMMAND"'

pre_deploy:
  <<: *ssh_script
  stage: pre_deploy
  variables:
    COMMAND: "${PRE_DEPLOY_CMD}"

# File‐system steps, implemented in shared scripts
prepare_release_dir:
  extends: .prepare_release_dir_template
  stage: deploy

upload_code:
  extends: .upload_code_template
  stage: deploy
  needs:
    - prepare_release_dir

extract_and_link:
  extends: .extract_and_link_template
  stage: deploy
  needs:
    - upload_code

# App‐specific commands still inline
backup_current:
  <<: *ssh_script
  stage: deploy
  variables:
    COMMAND: "${BACKUP_CMD}"
  needs:
    - extract_and_link

stop_app:
  <<: *ssh_script
  stage: deploy
  variables:
    COMMAND: "${STOP_CMD}"
  needs:
    - backup_current

start_app:
  <<: *ssh_script
  stage: deploy
  variables:
    COMMAND: "${START_CMD}"
  needs:
    - stop_app

verify_health:
  <<: *ssh_script
  stage: post_deploy
  variables:
    COMMAND: "${VERIFY_CMD}"
  needs:
    - start_app

smoke_tests:
  <<: *ssh_script
  stage: post_deploy
  variables:
    COMMAND: "${SMOKE_CMD}"
  needs:
    - verify_health

cleanup:
  <<: *ssh_script
  stage: post_deploy
  variables:
    COMMAND: "${CLEANUP_CMD}"
  needs:
    - smoke_tests

notify:
  <<: *ssh_script
  stage: post_deploy
  variables:
    COMMAND: "${NOTIFY_CMD}"
  needs:
    - cleanup