include:
  - project: 'experiments/ci-templates'
    ref: 'development'
    file: 'templates/cd-templates.yml'

variables:
  # Deployment target
  DEPLOY_SERVER: "mars.butterflycluster.com"
  DEPLOY_USER: "deploy_sa"
  DEPLOY_PATH: "/apps/myapp"
  ENV_NAME: "production"
  
  # Application commands
  PRE_DEPLOY_CMD: "df -h; free -m"
  BACKUP_CMD: "tar czf ${DEPLOY_PATH}/backup-$(date +%s).tgz ${DEPLOY_PATH}"
  STOP_CMD: "bash ${DEPLOY_PATH}/scripts/stop.sh"
  START_CMD: "bash ${DEPLOY_PATH}/scripts/start.sh"
  VERIFY_CMD: "curl -sSf http://localhost:8080/health"
  SMOKE_CMD: "bash ${DEPLOY_PATH}/scripts/smoke_test.sh"
  CLEANUP_CMD: "rm -f ${DEPLOY_PATH}/*.log; find ${DEPLOY_PATH}/tmp -mtime +7 -delete"

stages:
  - pre_deploy
  - deploy
  - post_deploy

# Deployment Pipeline
pre_deploy:
  extends: .pre_deploy_job
  variables:
    SSH_COMMAND: "${PRE_DEPLOY_CMD}"

transfer_code:
  extends: .transfer_job

backup_current:
  extends: .backup_job
  variables:
    SSH_COMMAND: "${BACKUP_CMD}"
  needs: [transfer_code]

stop_app:
  extends: .stop_job
  variables:
    SSH_COMMAND: "${STOP_CMD}"
  needs: [backup_current]

start_app:
  extends: .start_job
  variables:
    SSH_COMMAND: "${START_CMD}"
  needs: [stop_app]

verify_health:
  extends: .verify_job
  variables:
    SSH_COMMAND: "${VERIFY_CMD}"
  needs: [start_app]

smoke_tests:
  extends: .smoke_job
  variables:
    SSH_COMMAND: "${SMOKE_CMD}"
  needs: [verify_health]

cleanup:
  extends: .cleanup_job
  variables:
    SSH_COMMAND: "${CLEANUP_CMD}"
  needs: [smoke_tests]
  