services:
  dashapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLOBAL_INDEX_URL: ${GLOBAL_INDEX_URL}
        GLOBAL_CERT: ${GLOBAL_CERT}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    ports:
      - "8050:8050"
    env_file:
      - .env
    environment:
      - PYTHONIOENCODING=utf-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - .:/app
    restart: unless-stopped