profile_data = {
    'Repo ID': 'CTFd',
    'Status': 'ACTIVE',
    'Security Risk': True,
    'EOL Risk': False,
    'Tech Debt Risk': True,
    'Repo Size (MB)': 25,
    'File Count': 929,
    'Lines of Code': 106417,
    'Total NLOC': 95432,
    'Blank Lines': 12345,
    'Comment Lines': 8540,
    'Avg Cyclomatic Complexity': 3.5,
    'Total Cyclomatic Complexity': 2200,
    'Total Tokens': 560000,
    'Total Functions': 1250,
    'Classification Label': 'Medium',
    'Contributors': 149,
    'Repo Age (Years)': 10,
    'Last Commit Date': '2024-12-27',
    'Activity Status': 'ACTIVE',
    'Active Branch Count': 1,
    'Main Language': 'Python',
    'Other Languages': ['HTML', 'Shell'],
    'Frameworks': ['Flask', 'Jinja2'],
    'Build Tool': 'Poetry',
    'Runtime Version': 'Python 3.9',
    'Language Percentages': {
        'Python': 85,
        'HTML': 10,
        'Shell': 5,
    },
    'Dockerfile': True,
    'CI/CD Present': True,
    'IaC Config Present': True,
    'Deprecated APIs Found': 3,
    'Hardcoded Secrets Found': 2,
    'Other Modernization Findings': 8,
    'Health Scores': {
        'Code Quality': 80,
        'Security': 40,
        'Modernization': 60,
        'IaC Readiness': 50,
    },
    'Cyclomatic Complexity Avg': 3.5,
    'Cyclomatic Complexity Max': 12,
    'Comment Density': 12,
    'Total Dependencies': 5,
    'Outdated Dependencies %': 40,
    'Vulnerable Dependencies %': 20,
    'Critical Vuln Count': 1,
    'EOL Packages Found': 1,
    'Dependency Managers Used': ['PyPI'],
    'Monolith Risk': 'Low',
    'Single Developer Risk': False,
    'DevOps Best Practices': True,
    'Commits Last 12 Months': [5, 10, 8, 15, 9, 12, 6, 14, 11, 7, 13, 10],

    # This is the only piece section_dependencies_risk_by_subcategory.py needs:
    'Dependencies': [
        {
            "name": "Flask",
            "version": "1.0",
            "package_type": "PyPI",
            "category": "Application Development",
            "sub_category": "Web Frameworks",
        },
        {
            "name": "psycopg2",
            "version": "2.8",
            "package_type": "PyPI",
            "category": "Data Management & Storage",
            "sub_category": "Relational Databases",
        },
        {
            "name": "requests",
            "version": "2.22.0",
            "package_type": "PyPI",
            "category": "Utilities & Libraries",
            "sub_category": "General-Purpose",
        },
        {
            "name": "gunicorn",
            "version": "20.0.4",
            "package_type": "PyPI",
            "category": "Infrastructure & Deployment",
            "sub_category": "Containerization & Orchestration",
        },
        {
            "name": "bcrypt",
            "version": "3.2.0",
            "package_type": "PyPI",
            "category": "Security & Identity",
            "sub_category": "Authentication",
        },
    ],
    'Vulnerabilities': [
    {
        'package': 'flask',
        'version': '1.0',
        'severity': 'Critical',
        'fix_version': '2.0',
        'source': 'G'
    },
    {
        'package': 'requests',
        'version': '2.8',
        'severity': 'High',
        'fix_version': '2.25.1',
        'source': 'T'
    }
]
}