RC_COLUMNS_BY_TABLE_ID = {
    "overview": [
        "rc.repo_size_bytes",
        "rc.file_count",
        "rc.code_size_bytes",
        "rc.dependency_count",
        "rc.package_types",
        "rc.top_packages",
        "rc.iac_frameworks",
    ],
    "build-info": [
        "rc.runtime_version",
        "rc.build_tool_version",
        "rc.repo_size_bytes",
        "rc.file_count",
        "rc.code_size_bytes",
    ],
    "code-insights": [
        "rc.total_blank",
        "rc.total_comment",
        "rc.total_lines_of_code",
        "rc.source_code_file_count",
        "rc.total_semgrep_findings",
        "rc.cat_best_practice",
        "rc.cat_compatibility",
        "rc.cat_correctness",
        "rc.cat_maintainability",
        "rc.cat_performance",
        "rc.cat_portability",
        "rc.cat_security",
        "rc.lizard_total_nloc",
        "rc.lizard_total_ccn",
    ],
    "dependencies": [
        "rc.grype_total_vulns",
        "rc.grype_fixable_vulns",
        "rc.grype_critical_fixable",
        "rc.grype_high_fixable",
        "rc.grype_medium_fixable",
        "rc.grype_low_fixable",
        "rc.total_trivy_vulns",
        "rc.trivy_critical",
        "rc.trivy_high",
        "rc.trivy_medium",
        "rc.trivy_low",
        "rc.xeol_eol_package_count",
        "rc.xeol_earliest_eol_date",
        "rc.eol_package_count",
        "rc.earliest_eol_date",
    ]
}